services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: jarikkomarik
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    #hostname: rabbitmq-host
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
  customer:
    image: jarikkomarik/customer:latest
    container_name: customer
    ports:
      - "8080:8080"
    environment:
          - SPRING_PROFILES_ACTIVE=docker
          - spring_rabbitmq_host=rabbitmq
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
    networks:
      - spring
      - postgres
  fraud:
    image: jarikkomarik/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    environment:
          - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - postgres
    networks:
      - spring
      - postgres
  notification:
    image: jarikkomarik/notification:latest
    container_name: notification
    ports:
      - "8082:8082"
    environment:
          - SPRING_PROFILES_ACTIVE=docker
          - spring_rabbitmq_host=rabbitmq
    depends_on:
      - zipkin
      - rabbitmq
      - postgres
    networks:
      - spring
      - postgres
networks:
  postgres:
    driver: bridge
  spring:

volumes:
  postgres:
  pgadmin: